### ISSUE TITLE
Definição de template do projeto

### ISSUE THREAD

**Issue by leticiacamposs2** [React-Bootcamp-WoMarkersCode/cv-speed-hiring#1]

**Comment by annacia** [comment]
Reactstrap
https://reactstrap.github.io/

Paper Kit React
https://demos.creative-tim.com/paper-kit-react/#/index

**Comment by leticiacamposs2** [comment]
Gostei desse dashboard porque ele já esta divido em páginas e tem bastante componentes legais:
https://demos.creative-tim.com/light-bootstrap-dashboard-react/#/admin/dashboard

**Comment by lalizita** [comment]
Conheço alguns também:
https://ant.design/ (meu favorito e a prof Brennda usou nos exemplos de Redux)
https://github.com/TarikHuber/react-most-wanted
https://rebassjs.org/

**Comment by lalizita** [comment]
Apesar que eu achei o paper kit mt legal tbm

**Comment by leticiacamposs2** [comment]
Meninas foi definido que o template a ser utilizado é o Paper Kit React certo? Sendo assim já podemos encerrar esta issue ne?
