### ISSUE TITLE
Enviar a solicitação da chave de acesso

### ISSUE THREAD

**Issue by dayanamaia** [React-Bootcamp-WoMarkersCode/cv-speed-hiring#76]
Envia o form de solicitar a chave de acesso
Nome da empresa que precisa acessar os curriculos
email do solicitante

Se não engano existe uma funcionalidade do firebase de enviar e-mail após uma atualização no banco.

**Comment by leticiacamposs2** [comment]
Este tutorial do medium pode ajudar:

**"Como enviar e-mails usando Cloud Functions do Firebase com o Nodemailer"**

 https://medium.com/@adsonrocha/como-enviar-e-mails-usando-cloud-functions-do-firebase-com-o-nodemailer-5c8bf6d9f8e8
